spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboottest?characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456

server:
  port: 8080

swagger:
  enabled: true